"""
Phase 18 (2026-04-21) — Topení 2 page (weekly schedule editor)

Nová stránka 📅 TOPENÍ 2 s editorem týdenního programu per zóna:
  - Zone picker (4 zóny)
  - Day tabs (Po-Ne)
  - Sloty (from, to, temp) — add / remove / edit
  - 24h preview bar (colored segments podle teplot)
  - Save → JSON do sh_heating_schedule_<zone>

Idempotentní — marker page-heating2.
"""
import os, re, sys

FILES = [
    r'C:\HOMEY PRO 2026\dasboardy_CLAUDE\smart_home_rpi.html',
    r'C:\HOMEY PRO 2026\dasboardy_CLAUDE\smart_home_1920x1080.html',
    r'C:\HOMEY PRO 2026\dasboardy_CLAUDE\smart_home_2880x1800.html',
]

MARKER = 'id="page-heating2"'

# ═══════════════════════════════════════════════════════════════════════════
# HTML — nová page "TOPENÍ 2"
# ═══════════════════════════════════════════════════════════════════════════
PAGE_HTML = '''
  <!-- ═══════════ PAGE: TOPENÍ 2 (weekly editor) ═══════════ -->
  <div class="page" id="page-heating2">
    <div style="height:14px;flex-shrink:0;"></div>

    <div class="sect" style="color:var(--orange);">
      <span class="help-sect-header">
        <span>📅 TOPENÍ 2 — Týdenní program</span>
        <button class="help-btn" data-help-for="help-heating2" onclick="toggleHelp('help-heating2')">ℹ</button>
      </span>
    </div>
    <div id="help-heating2" class="help-panel">
      <h4>📅 Ruční plánování teplot</h4>
      <ul>
        <li>Vyber <strong>zónu</strong> a <strong>den</strong> → zobrazí sloty (časová okna s teplotou)</li>
        <li><strong>+ Přidat slot</strong> → nové časové okno (from, to, teplota)</li>
        <li><strong>×</strong> u slotu → smazat</li>
        <li><strong>💾 Uložit</strong> → zapíše do <code>sh_heating_schedule_&lt;zone&gt;</code> (JSON)</li>
        <li>Scheduler (každých 5 min) přečte program a nastaví target per zóna</li>
      </ul>
      <p><strong>Režim MANUAL</strong>: sloty se aplikují 1:1. <strong>AUTO</strong>: sloty jako baseline + AI úpravy.</p>
    </div>

    <!-- Zone + Day picker -->
    <div class="card" style="padding:10px;">
      <div style="display:flex;gap:8px;align-items:center;margin-bottom:8px;">
        <span style="font-size:12px;">Zóna:</span>
        <select id="h2-zone-picker" onchange="h2LoadSchedule()"
                style="background:var(--bg2);border:1px solid var(--bd);color:var(--tx1);padding:4px 8px;border-radius:var(--r2);font-size:12px;">
          <option value="jidelna">🍽 Jídelna</option>
          <option value="loznice">🛏 Ložnice</option>
          <option value="koupelna">🚿 Koupelna</option>
          <option value="toaleta">🚽 Toaleta</option>
        </select>
        <span style="margin-left:auto;font-size:10px;color:var(--tx3);" id="h2-zone-status">—</span>
      </div>
      <div class="btn-row" style="flex-wrap:wrap;" id="h2-day-tabs">
        <!-- day tabs generated by JS -->
      </div>
    </div>

    <!-- Slots editor -->
    <div class="sect" style="color:var(--orange);margin-top:12px;">ČASOVÉ BLOKY</div>
    <div class="card" style="padding:10px;">
      <div id="h2-slots-list"></div>
      <div style="display:flex;gap:8px;margin-top:10px;">
        <div class="btn" onclick="h2AddSlot()">+ Přidat slot</div>
        <div class="btn" onclick="h2CopyFromYesterday()" style="border-color:var(--cyan);color:var(--cyan);">📋 Kopírovat z včerejška</div>
        <div class="btn" onclick="h2Save()" style="margin-left:auto;border-color:var(--green);color:var(--green);">💾 Uložit</div>
      </div>
    </div>

    <!-- 24h preview -->
    <div class="sect" style="color:var(--orange);margin-top:12px;">NÁHLED 24H</div>
    <div class="card" style="padding:10px;">
      <div id="h2-preview-bar" style="height:28px;background:var(--bg3);border-radius:4px;position:relative;overflow:hidden;"></div>
      <div style="display:flex;justify-content:space-between;font-size:9px;color:var(--tx3);margin-top:4px;font-family:var(--mono);">
        <span>0</span><span>3</span><span>6</span><span>9</span><span>12</span><span>15</span><span>18</span><span>21</span><span>24</span>
      </div>
      <div id="h2-preview-legend" style="font-size:10px;color:var(--tx2);margin-top:8px;"></div>
    </div>

    <div style="height:24px;flex-shrink:0;"></div>
  </div>
'''

# ═══════════════════════════════════════════════════════════════════════════
# CSS
# ═══════════════════════════════════════════════════════════════════════════
CSS_HTML = '''
/* Phase 18 heating2 editor */
.h2-day-btn{padding:6px 10px;font-size:11px;border:1px solid var(--bd);border-radius:var(--r2);background:var(--bg2);color:var(--tx2);cursor:pointer;font-family:var(--mono);}
.h2-day-btn:hover{border-color:var(--cyan);}
.h2-day-btn.active{background:var(--orange);color:var(--bg1);border-color:var(--orange);font-weight:600;}
.h2-slot-row{display:flex;gap:6px;align-items:center;padding:6px;border-bottom:1px solid var(--bd);font-family:var(--mono);font-size:12px;}
.h2-slot-row:last-child{border-bottom:none;}
.h2-slot-row input[type=time]{background:var(--bg2);border:1px solid var(--bd);color:var(--tx1);padding:3px 6px;border-radius:3px;font-family:var(--mono);font-size:11px;width:80px;}
.h2-slot-row input[type=number]{background:var(--bg2);border:1px solid var(--bd);color:var(--tx1);padding:3px 6px;border-radius:3px;font-family:var(--mono);font-size:11px;width:60px;}
.h2-slot-del{background:transparent;border:1px solid var(--red);color:var(--red);padding:2px 8px;border-radius:3px;cursor:pointer;font-size:10px;}
.h2-slot-del:hover{background:var(--red);color:var(--bg1);}
.h2-slot-arrow{color:var(--tx3);}
/* /Phase 18 */
'''

# ═══════════════════════════════════════════════════════════════════════════
# JS
# ═══════════════════════════════════════════════════════════════════════════
JS_CODE = '''

// ═════════ Phase 18 — HEATING 2 editor ═════════
const H2_DAYS = [
  { id: 'monday',    label: 'Po' },
  { id: 'tuesday',   label: 'Út' },
  { id: 'wednesday', label: 'St' },
  { id: 'thursday',  label: 'Čt' },
  { id: 'friday',    label: 'Pá' },
  { id: 'saturday',  label: 'So' },
  { id: 'sunday',    label: 'Ne' },
];

let h2State = {
  zone: 'jidelna',
  day: 'monday',
  scheduleObj: null,   // parsed JSON
  currentSlots: [],    // slots for current day
};

function h2TempColor(temp) {
  // Mapping teplot → barvy (blue cold → red hot)
  if (temp < 16) return '#4a6ee0';       // tmavá modrá (eco)
  if (temp < 18) return '#6aaeff';       // světlejší modrá (night)
  if (temp < 20) return '#5ec777';       // zelená (mírný comfort)
  if (temp < 22) return '#87d667';       // jasnější zelená (day)
  if (temp < 24) return '#ffa940';       // oranžová (teplejší)
  return '#ff6b6b';                       // červená (boost)
}

function h2MinutesOfDay(hhmm) {
  const p = String(hhmm || '00:00').split(':');
  return (Number(p[0])||0) * 60 + (Number(p[1])||0);
}

function h2InitDayTabs() {
  const c = document.getElementById('h2-day-tabs');
  if (!c) return;
  const todayIdx = new Date().getDay(); // 0=Ne, 1=Po...
  const todayDayId = H2_DAYS[(todayIdx + 6) % 7].id;  // convert to Mon-first
  c.innerHTML = H2_DAYS.map(d => {
    const isToday = d.id === todayDayId;
    return `<div class="h2-day-btn${h2State.day === d.id ? ' active' : ''}"
                 onclick="h2SwitchDay('${d.id}')">${d.label}${isToday ? ' •' : ''}</div>`;
  }).join('');
}

function h2SwitchDay(dayId) {
  h2State.day = dayId;
  h2InitDayTabs();
  h2RenderSlotsFromState();
}

async function h2LoadSchedule() {
  if (!varMapLoaded) await loadVarMap();
  const zonePicker = document.getElementById('h2-zone-picker');
  h2State.zone = zonePicker ? zonePicker.value : 'jidelna';

  const rawVar = ALL_VARS['sh_heating_schedule_' + h2State.zone];
  const raw = rawVar ? String(rawVar.value || '{}') : '{}';
  try {
    h2State.scheduleObj = JSON.parse(raw);
  } catch(e) {
    h2State.scheduleObj = { version: 1, enabled: true, schedule: {} };
  }
  if (!h2State.scheduleObj.schedule) h2State.scheduleObj.schedule = {};

  const status = document.getElementById('h2-zone-status');
  if (status) {
    const en = h2State.scheduleObj.enabled !== false ? 'enabled' : 'disabled';
    status.textContent = 'schedule ' + en;
  }

  h2RenderSlotsFromState();
}

function h2ResolveDaySlots(dayId) {
  // Handle "same_as:monday" aliases
  let slots = h2State.scheduleObj?.schedule?.[dayId];
  let aliasChain = [dayId];
  while (typeof slots === 'string' && slots.startsWith('same_as:')) {
    const ref = slots.replace('same_as:', '').trim();
    if (aliasChain.includes(ref)) break;
    aliasChain.push(ref);
    slots = h2State.scheduleObj.schedule[ref];
  }
  return Array.isArray(slots) ? slots : [];
}

function h2RenderSlotsFromState() {
  h2State.currentSlots = h2ResolveDaySlots(h2State.day).map(s => ({...s}));
  h2RenderSlotsList();
  h2RenderPreview();
}

function h2RenderSlotsList() {
  const c = document.getElementById('h2-slots-list');
  if (!c) return;

  if (h2State.currentSlots.length === 0) {
    c.innerHTML = '<div style="color:var(--tx3);font-size:11px;padding:10px;text-align:center;">Žádné sloty. Klikni <strong>+ Přidat</strong>.</div>';
    return;
  }

  c.innerHTML = h2State.currentSlots.map((s, idx) => `
    <div class="h2-slot-row">
      <input type="time" value="${s.from || '00:00'}" onchange="h2UpdateSlot(${idx}, 'from', this.value)">
      <span class="h2-slot-arrow">→</span>
      <input type="time" value="${s.to || '00:00'}" onchange="h2UpdateSlot(${idx}, 'to', this.value)">
      <span style="margin-left:auto;">🌡</span>
      <input type="number" step="0.5" min="7" max="28" value="${s.temp || 20}" onchange="h2UpdateSlot(${idx}, 'temp', Number(this.value))">
      <span>°C</span>
      <button class="h2-slot-del" onclick="h2RemoveSlot(${idx})">×</button>
    </div>
  `).join('');
}

function h2UpdateSlot(idx, field, value) {
  if (!h2State.currentSlots[idx]) return;
  h2State.currentSlots[idx][field] = value;
  h2RenderPreview();
}

function h2AddSlot() {
  // Default: 06:00–18:00, 21°C
  h2State.currentSlots.push({ from: '06:00', to: '18:00', temp: 21 });
  h2RenderSlotsList();
  h2RenderPreview();
}

function h2RemoveSlot(idx) {
  h2State.currentSlots.splice(idx, 1);
  h2RenderSlotsList();
  h2RenderPreview();
}

function h2CopyFromYesterday() {
  // Najdi předchozí day (Mon-first, wrap)
  const curIdx = H2_DAYS.findIndex(d => d.id === h2State.day);
  const prevIdx = (curIdx - 1 + 7) % 7;
  const prevDay = H2_DAYS[prevIdx].id;
  const prevSlots = h2ResolveDaySlots(prevDay);
  if (prevSlots.length === 0) {
    try { flash('Předchozí den nemá sloty'); } catch(_){}
    return;
  }
  h2State.currentSlots = prevSlots.map(s => ({...s}));
  h2RenderSlotsList();
  h2RenderPreview();
  try { flash('📋 Zkopírováno z ' + H2_DAYS[prevIdx].label); } catch(_){}
}

function h2RenderPreview() {
  const bar = document.getElementById('h2-preview-bar');
  const legend = document.getElementById('h2-preview-legend');
  if (!bar) return;

  const MINS = 1440;
  // Fill bar with segments
  const segments = [];
  const tempCounts = {};
  for (const s of h2State.currentSlots) {
    const fromM = h2MinutesOfDay(s.from);
    const toM = h2MinutesOfDay(s.to);
    const temp = Number(s.temp) || 20;
    if (fromM < toM) {
      segments.push({ from: fromM, to: toM, temp });
    } else {
      // wrap past midnight: rozděl na 2 segmenty
      segments.push({ from: fromM, to: MINS, temp });
      segments.push({ from: 0, to: toM, temp });
    }
    tempCounts[temp] = (tempCounts[temp] || 0) + (Math.abs(toM - fromM) || 0);
  }

  let html = '';
  for (const s of segments) {
    const left = (s.from / MINS) * 100;
    const width = ((s.to - s.from) / MINS) * 100;
    html += `<div style="position:absolute;left:${left}%;width:${width}%;height:100%;background:${h2TempColor(s.temp)};" title="${s.temp}°C">${width > 8 ? '<span style=\\'color:#fff;font-size:10px;line-height:28px;padding-left:4px;font-family:var(--mono);\\'>' + s.temp + '°</span>' : ''}</div>`;
  }
  bar.innerHTML = html;

  // Legend: jednoznačné teploty
  const uniqTemps = Object.keys(tempCounts).sort((a,b) => Number(a) - Number(b));
  legend.innerHTML = uniqTemps.map(t => `<span style="display:inline-block;padding:2px 6px;background:${h2TempColor(Number(t))};color:#fff;border-radius:3px;margin-right:6px;font-family:var(--mono);">${t} °C</span>`).join('') || '<span style="color:var(--tx3);">Žádné sloty</span>';
}

async function h2Save() {
  if (!varMapLoaded) await loadVarMap();
  if (!h2State.scheduleObj) h2State.scheduleObj = { version: 1, enabled: true, schedule: {} };

  // Validate slots (from must differ from to, temp in range)
  for (const s of h2State.currentSlots) {
    if (!s.from || !s.to) { flash('✗ Slot bez času'); return; }
    if (s.from === s.to) { flash('✗ Slot ' + s.from + ' shodná from a to'); return; }
    const t = Number(s.temp);
    if (!(t >= 7 && t <= 28)) { flash('✗ Temp mimo 7-28 °C'); return; }
  }

  // Update schedule for current day
  h2State.scheduleObj.schedule[h2State.day] = h2State.currentSlots.map(s => ({
    from: s.from, to: s.to, temp: Number(s.temp)
  }));

  // Make sure other days exist (set to same_as:monday if missing)
  for (const d of H2_DAYS) {
    if (!(d.id in h2State.scheduleObj.schedule)) {
      h2State.scheduleObj.schedule[d.id] = 'same_as:monday';
    }
  }

  const varName = 'sh_heating_schedule_' + h2State.zone;
  const jsonStr = JSON.stringify(h2State.scheduleObj);

  try {
    await writeVar(varName, jsonStr);
    if (ALL_VARS[varName]) ALL_VARS[varName].value = jsonStr;
    try { flash('💾 Uloženo: ' + h2State.zone + ' / ' + h2State.day); } catch(_){}
  } catch(e) {
    try { flash('✗ ' + e.message); } catch(_){}
  }
}

// Hook: když user otevře page-heating2, načti schedule
(function() {
  const _origSwitch = window.switchPage || function(){};
  window.switchPage = function(name) {
    _origSwitch(name);
    if (name === 'heating2') {
      setTimeout(() => {
        h2InitDayTabs();
        h2LoadSchedule();
      }, 100);
    }
  };
})();

document.addEventListener('DOMContentLoaded', () => {
  setTimeout(() => { h2InitDayTabs(); }, 1500);
});
// ═════════ /Phase 18 ═════════
'''

# Bottom nav tab
NAV_TAB_HTML = '<div class="tab"        id="tab-heating2" onclick="switchPage(\'heating2\')"><span class="ti">📅</span>PLÁN</div>\n  '

# Insert za tab-heating
NAV_ANCHOR = re.compile(
    r'(<div class="tab"\s+id="tab-heating"[^<]*onclick="switchPage\(\'heating\'\)"[^>]*>[^<]*<span class="ti">[^<]*</span>TOPENÍ</div>\s*\n\s*)'
)

# Insert page: před page-heating end closing div (before ADVANCED)
PAGE_ANCHOR = re.compile(
    r'(<!-- ═+ NEW: ADVANCED PAGE ═+ -->)'
)

# CSS insert before </style>
CSS_ANCHOR = re.compile(r'(</style>)')

# JS insert — za phase 16/17
JS_ANCHOR = re.compile(
    r'(// ═+ /Phase 16 ═+|// ═+ /Phase 15c ═+|</script>\s*</body>)',
    re.IGNORECASE
)


def patch_file(path):
    if not os.path.exists(path):
        print(f'  ✗ NOT FOUND: {path}')
        return False
    with open(path, 'r', encoding='utf-8') as f:
        html = f.read()
    if MARKER in html:
        print(f'  ✓ already patched: {os.path.basename(path)}')
        return True
    orig_len = len(html)

    # 1. Nav tab
    m = NAV_ANCHOR.search(html)
    if m:
        html = html[:m.end(1)] + NAV_TAB_HTML + html[m.end():]
    else:
        print(f'  ⚠ nav anchor nenalezen: {os.path.basename(path)}')

    # 2. Page insert
    m2 = PAGE_ANCHOR.search(html)
    if m2:
        html = html[:m2.start()] + PAGE_HTML + '\n\n  ' + m2.group(0) + html[m2.end():]
    else:
        print(f'  ✗ page anchor not found: {os.path.basename(path)}')
        return False

    # 3. CSS
    m3 = CSS_ANCHOR.search(html)
    if m3:
        html = html[:m3.start()] + CSS_HTML + m3.group(0) + html[m3.end():]

    # 4. JS
    m4 = JS_ANCHOR.search(html)
    if m4:
        html = html[:m4.start()] + JS_CODE + '\n\n' + m4.group(0) + html[m4.end():]
    else:
        html = html.replace('</script>\n</body>', JS_CODE + '\n</script>\n</body>', 1)

    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f'  ✓ patched: {os.path.basename(path)} ({len(html)-orig_len:+d} bytes)')
    return True


def main():
    print('Phase 18: Heating 2 weekly editor')
    ok = 0
    for p in FILES:
        if patch_file(p):
            ok += 1
    print(f'\nDone: {ok}/{len(FILES)} files patched')
    return 0 if ok == len(FILES) else 1


if __name__ == '__main__':
    sys.exit(main())
