"""
Phase 16 (2026-04-21) — Heating page (Fáze A MVP)
Přidá novou stránku "🔥 TOPENÍ" do dashboardu:
  - Master card: mode toggle (auto/manual/off), preset, boiler state + runtime kWh
  - 4× zone tiles: jídelna, ložnice, koupelna, toaleta
  - Quick actions: Doma, Odjíždím, Boost 30min, Noc, Vše OFF
  - Schedule viewer (read-only) — každá zóna + aktuální slot
  - Bottom nav tab "🔥 TOPENÍ" (mezi ZÓNY a AUDIO)

Idempotentní — marker page-heating.
Deploy na všechny 3 rozlišení (rpi, 1920, 2880).
"""
import os, re, sys

FILES = [
    r'C:\HOMEY PRO 2026\dasboardy_CLAUDE\smart_home_rpi.html',
    r'C:\HOMEY PRO 2026\dasboardy_CLAUDE\smart_home_1920x1080.html',
    r'C:\HOMEY PRO 2026\dasboardy_CLAUDE\smart_home_2880x1800.html',
]

MARKER = 'id="page-heating"'

# ═══════════════════════════════════════════════════════════════════════════
# 1. HTML — nová page TOPENÍ
# ═══════════════════════════════════════════════════════════════════════════
PAGE_HTML = '''
  <!-- ═══════════ PAGE: TOPENÍ (Fáze A MVP) ═══════════ -->
  <div class="page" id="page-heating">
    <div style="height:14px;flex-shrink:0;"></div>

    <div class="sect" style="color:var(--orange);">
      <span class="help-sect-header">
        <span>🔥 TOPENÍ — Protherm RAY 9 KE</span>
        <button class="help-btn" data-help-for="help-heating" onclick="toggleHelp('help-heating')">ℹ</button>
      </span>
    </div>
    <div id="help-heating" class="help-panel">
      <h4>🔥 Topení — jak to funguje</h4>
      <ul>
        <li><strong>🤖 Auto</strong> — systém se řídí sám podle schedule + AI vrstev (pre-wake, weather, occupancy)</li>
        <li><strong>📅 Manual</strong> — topí přesně dle týdenního programu, žádné AI úpravy</li>
        <li><strong>⏸ Off</strong> — vše vypnuto, anti-freeze 7 °C stále aktivní</li>
      </ul>
      <p><strong>Preset:</strong> 🏠 Doma = standardní · 🚗 Odjíždím = všechny zóny 16 °C · 🔥 Boost = +2 °C na 30 min</p>
      <p><strong>kWh dnes</strong> = runtime × 9 kW (odhad, Protherm moduluje interně).</p>
    </div>

    <!-- MASTER CARD -->
    <div class="card" style="padding:12px;">
      <div class="tog-row" style="margin-bottom:8px;">
        <span class="card-icon">🎛</span>
        <span class="tog-lbl" style="flex:1;">Režim</span>
        <div class="mode-btns" style="display:flex;gap:4px;">
          <button class="heat-mode-btn" data-mode="auto"   onclick="setHeatingMode('auto')">🤖 Auto</button>
          <button class="heat-mode-btn" data-mode="manual" onclick="setHeatingMode('manual')">📅 Manual</button>
          <button class="heat-mode-btn" data-mode="off"    onclick="setHeatingMode('off')">⏸ Off</button>
        </div>
      </div>
      <div class="divider"></div>
      <div style="display:flex;gap:16px;padding:8px 0;font-family:var(--mono);font-size:12px;">
        <div>Preset: <strong id="heat-preset">—</strong></div>
        <div>Demand: <strong id="heat-demand">0/4</strong> zón</div>
      </div>
      <div class="divider"></div>
      <div style="display:flex;gap:16px;padding:8px 0;font-family:var(--mono);font-size:12px;">
        <div>Kotel: <strong id="heat-boiler-state">—</strong></div>
        <div>Runtime dnes: <strong id="heat-runtime">0 min</strong></div>
        <div>≈ <strong id="heat-kwh">0 kWh</strong></div>
      </div>
    </div>

    <!-- ZÓNY -->
    <div class="sect" style="color:var(--orange);margin-top:12px;">ZÓNY</div>
    <div class="tile-grid g2" id="heat-zones-grid">
      <!-- 4 zone tiles generated by JS -->
    </div>

    <!-- RYCHLÉ AKCE -->
    <div class="sect" style="color:var(--orange);margin-top:12px;">RYCHLÉ AKCE</div>
    <div class="btn-row" style="flex-wrap:wrap;">
      <div class="btn" onclick="setHeatingPreset('home')">🏠 Doma</div>
      <div class="btn" onclick="setHeatingPreset('away')">🚗 Odjíždím</div>
      <div class="btn" onclick="setHeatingBoost(30)">🔥 Boost 30 min</div>
      <div class="btn" onclick="setHeatingPreset('home'); setHeatingNightAll()">🌙 Noc</div>
      <div class="btn" style="border-color:var(--red);color:var(--red);" onclick="setHeatingMode('off')">⏸ Vše OFF</div>
    </div>

    <!-- SCHEDULE VIEWER -->
    <div class="sect" style="color:var(--orange);margin-top:12px;">TÝDENNÍ PROGRAM (read-only MVP)</div>
    <div class="card" style="padding:10px;font-family:var(--mono);font-size:11px;color:var(--tx2);">
      <div>Editor přijde v Fázi B. Zatím úprava přes Homey Logic nebo CONFIG page (JSON).</div>
      <div id="heat-schedule-preview" style="margin-top:8px;"></div>
    </div>

    <div style="height:24px;flex-shrink:0;"></div>
  </div>
'''

# ═══════════════════════════════════════════════════════════════════════════
# 2. CSS pro heating page (mode-btns, zone-tile)
# ═══════════════════════════════════════════════════════════════════════════
CSS_HTML = '''
/* Phase 16 heating */
.heat-mode-btn{padding:6px 10px;font-size:11px;border:1px solid var(--bd);border-radius:var(--r2);background:var(--bg2);color:var(--tx2);cursor:pointer;font-family:var(--mono);transition:all .15s;}
.heat-mode-btn:hover{border-color:var(--cyan);color:var(--cyan);}
.heat-mode-btn.active{background:var(--orange);border-color:var(--orange);color:var(--bg1);font-weight:600;}
.heat-zone-tile{background:var(--bg2);border:1px solid var(--bd);border-radius:var(--r2);padding:10px;}
.heat-zone-tile .zone-hdr{display:flex;align-items:center;gap:6px;font-size:13px;margin-bottom:4px;}
.heat-zone-tile .zone-temps{display:flex;justify-content:space-between;font-family:var(--mono);font-size:12px;}
.heat-zone-tile .zone-temps .curr{color:var(--cyan);font-weight:600;}
.heat-zone-tile .zone-temps .tgt{color:var(--orange);}
.heat-zone-tile .zone-bar{height:4px;background:var(--bg3);border-radius:2px;margin-top:6px;overflow:hidden;}
.heat-zone-tile .zone-bar-fill{height:100%;background:linear-gradient(90deg,var(--cyan),var(--orange));transition:width .3s;}
/* /Phase 16 */
'''

# ═══════════════════════════════════════════════════════════════════════════
# 3. JS — rendering + actions
# ═══════════════════════════════════════════════════════════════════════════
JS_CODE = '''

// ═════════ Phase 16 — HEATING ═════════
const HEAT_ZONES = [
  { id: 'jidelna',  icon: '🍽', label: 'Jídelna'  },
  { id: 'loznice',  icon: '🛏', label: 'Ložnice'  },
  { id: 'koupelna', icon: '🚿', label: 'Koupelna' },
  { id: 'toaleta',  icon: '🚽', label: 'Toaleta'  }
];

async function refreshHeating() {
  try {
    if (!varMapLoaded) await loadVarMap();

    // Master
    const mode    = String((ALL_VARS['sh_heating_mode'] || {}).value || 'manual').toLowerCase();
    const preset  = String((ALL_VARS['sh_heating_preset'] || {}).value || 'home').toLowerCase();
    const state   = String((ALL_VARS['sh_heating_boiler_state'] || {}).value || 'off').toLowerCase();
    const demand  = Number((ALL_VARS['sh_heating_demand_count'] || {}).value || 0);
    const rtSec   = Number((ALL_VARS['sh_heating_runtime_today_s'] || {}).value || 0);
    const kotelKw = Number((ALL_VARS['sh_cfg_heating_kotel_kw'] || {}).value || 9);
    const kwh     = Math.round((rtSec / 3600) * kotelKw * 10) / 10;

    document.querySelectorAll('.heat-mode-btn').forEach(b => {
      b.classList.toggle('active', b.dataset.mode === mode);
    });
    const presetEl = document.getElementById('heat-preset');
    if (presetEl) {
      const presetLbl = { home: '🏠 Doma', away: '🚗 Pryč', boost: '🔥 Boost', override: '✋ Override' }[preset] || preset;
      presetEl.textContent = presetLbl;
    }
    const stateEl = document.getElementById('heat-boiler-state');
    if (stateEl) {
      stateEl.innerHTML = state === 'on'
        ? '<span style="color:var(--red);">🔴 ON</span>'
        : '<span style="color:var(--tx3);">⚫ OFF</span>';
    }
    const demEl = document.getElementById('heat-demand');
    if (demEl) demEl.textContent = demand + '/' + HEAT_ZONES.length;
    const rtEl = document.getElementById('heat-runtime');
    if (rtEl) {
      const h = Math.floor(rtSec / 3600);
      const m = Math.floor((rtSec % 3600) / 60);
      rtEl.textContent = (h > 0 ? h + ' h ' : '') + m + ' min';
    }
    const kwhEl = document.getElementById('heat-kwh');
    if (kwhEl) kwhEl.textContent = kwh + ' kWh';

    // Zones
    const grid = document.getElementById('heat-zones-grid');
    if (grid) {
      grid.innerHTML = HEAT_ZONES.map(z => {
        const enabled = String((ALL_VARS['sh_heating_zone_' + z.id + '_enabled'] || {}).value || 'yes').toLowerCase() === 'yes';
        const curr = Number((ALL_VARS['sh_heating_zone_' + z.id + '_current_temp'] || {}).value || -99);
        const tgt = Number((ALL_VARS['sh_heating_zone_' + z.id + '_target_temp'] || {}).value || 20);
        const currTxt = curr > 0 ? curr.toFixed(1) + ' °C' : '— °C';
        const tgtTxt = tgt.toFixed(1) + ' °C';
        const pct = curr > 0 ? Math.max(0, Math.min(100, ((curr - 10) / (28 - 10)) * 100)) : 0;
        const heating = (tgt - curr) > 0.3 && curr > 0;
        const borderColor = !enabled ? 'var(--tx3)' : heating ? 'var(--orange)' : 'var(--bd)';
        return `<div class="heat-zone-tile" style="border-color:${borderColor};">
          <div class="zone-hdr">
            <span>${z.icon}</span>
            <strong>${z.label}</strong>
            ${!enabled ? '<span style="color:var(--tx3);font-size:10px;margin-left:auto;">off</span>' : heating ? '<span style="color:var(--orange);font-size:10px;margin-left:auto;">🔥 topí</span>' : ''}
          </div>
          <div class="zone-temps">
            <span class="curr">${currTxt}</span>
            <span class="tgt">→ ${tgtTxt}</span>
          </div>
          <div class="zone-bar"><div class="zone-bar-fill" style="width:${pct}%;"></div></div>
        </div>`;
      }).join('');
    }

    // Schedule preview (dnes pro každou zónu — aktuální slot)
    const schedPrev = document.getElementById('heat-schedule-preview');
    if (schedPrev) {
      const lines = HEAT_ZONES.map(z => {
        const raw = String((ALL_VARS['sh_heating_schedule_' + z.id] || {}).value || '{}');
        let tgt = Number((ALL_VARS['sh_heating_zone_' + z.id + '_target_temp'] || {}).value || 20);
        return z.icon + ' ' + z.label + ': aktuálně → ' + tgt.toFixed(1) + ' °C';
      });
      schedPrev.innerHTML = lines.join('<br>');
    }

  } catch(e) { log('[HEAT] refresh err: ' + e.message); }
}

async function setHeatingMode(mode) {
  try {
    if (!varMapLoaded) await loadVarMap();
    await writeVar('sh_heating_mode', mode);
    if (ALL_VARS['sh_heating_mode']) ALL_VARS['sh_heating_mode'].value = mode;
    flash('🔥 Režim topení: ' + mode);
    setTimeout(refreshHeating, 200);
  } catch(e) { flash('✗ ' + e.message); }
}

async function setHeatingPreset(preset) {
  try {
    if (!varMapLoaded) await loadVarMap();
    await writeVar('sh_heating_preset', preset);
    if (ALL_VARS['sh_heating_preset']) ALL_VARS['sh_heating_preset'].value = preset;
    flash('🎯 Preset: ' + preset);
    setTimeout(refreshHeating, 200);
  } catch(e) { flash('✗ ' + e.message); }
}

async function setHeatingBoost(minutes) {
  try {
    if (!varMapLoaded) await loadVarMap();
    const until = Math.floor(Date.now() / 1000) + minutes * 60;
    for (const z of HEAT_ZONES) {
      const curTgt = Number((ALL_VARS['sh_heating_zone_' + z.id + '_target_temp'] || {}).value || 20);
      const boostDelta = Number((ALL_VARS['sh_cfg_heating_boost_delta'] || {}).value || 2);
      await writeVar('sh_heating_zone_' + z.id + '_manual_override_temp', curTgt + boostDelta);
      await writeVar('sh_heating_zone_' + z.id + '_manual_override_until_ts', until);
    }
    await writeVar('sh_heating_preset', 'boost');
    flash('🔥 Boost +2 °C / ' + minutes + ' min');
    setTimeout(refreshHeating, 200);
  } catch(e) { flash('✗ ' + e.message); }
}

async function setHeatingNightAll() {
  try {
    if (!varMapLoaded) await loadVarMap();
    // Force night target per zone (override expires at 6:00 tomorrow)
    const tomorrow6 = new Date();
    tomorrow6.setDate(tomorrow6.getDate() + 1);
    tomorrow6.setHours(6, 0, 0, 0);
    const until = Math.floor(tomorrow6.getTime() / 1000);
    const nightTemps = { jidelna: 18, loznice: 17, koupelna: 19, toaleta: 16 };
    for (const z of HEAT_ZONES) {
      await writeVar('sh_heating_zone_' + z.id + '_manual_override_temp', nightTemps[z.id] || 18);
      await writeVar('sh_heating_zone_' + z.id + '_manual_override_until_ts', until);
    }
    flash('🌙 Noční teploty do 6:00');
    setTimeout(refreshHeating, 200);
  } catch(e) { flash('✗ ' + e.message); }
}

// Hook into existing refresh cycle
(function() {
  const _origRefreshAll = window.refreshAll || (async () => {});
  window.refreshAll = async function() {
    try { await _origRefreshAll(); } catch(_) {}
    try { await refreshHeating(); } catch(_) {}
  };
})();

// Refresh on page show
document.addEventListener('DOMContentLoaded', () => {
  setTimeout(refreshHeating, 1500);
});
// ═════════ /Phase 16 ═════════
'''

# ═══════════════════════════════════════════════════════════════════════════
# 4. Bottom nav tab — vložit mezi ZÓNY a AUDIO
# ═══════════════════════════════════════════════════════════════════════════
NAV_TAB_HTML = '''<button class="nav-btn" data-page="heating" onclick="switchPage('heating')"><span class="nav-icon">🔥</span><span class="nav-lbl">TOPENÍ</span></button>
    '''

# Anchor v bottom nav — hledáme ZÓNY nav button, za něj vložíme TOPENÍ
NAV_ANCHOR = re.compile(
    r'(<button class="nav-btn" data-page="zones"[^>]*>.*?</button>\s*\n\s*)',
    re.DOTALL
)

# Page insert anchor — před </body> nebo před první existující dashboard page
# Použijeme marker za posledním <div class="page" id="page-advanced"> až po jeho </div>
# Lepší: najdeme "</div>\s*<!-- ═+ NEW: ADVANCED" a vložíme před to
# Alternativa: najdeme komentář końca pages nebo explicit marker
PAGE_INSERT_ANCHOR = re.compile(
    r'(<!-- ═+ NEW: ADVANCED PAGE ═+ -->)'
)

# CSS insert — před </style>
CSS_ANCHOR = re.compile(r'(</style>)')

# JS insert — před </script> posledního skriptu před </body>
# Alternativa: najít existující function refreshAll nebo DOMContentLoaded
JS_ANCHOR = re.compile(
    r'(// ═+ /Phase 15c ═+|// ═+ /Phase 15 ═+|</script>\s*</body>)',
    re.IGNORECASE
)


def patch_file(path):
    if not os.path.exists(path):
        print(f'  ✗ NOT FOUND: {path}')
        return False

    with open(path, 'r', encoding='utf-8') as f:
        html = f.read()

    if MARKER in html:
        print(f'  ✓ already patched: {os.path.basename(path)}')
        return True

    orig_len = len(html)
    changed = False

    # 1. Insert nav tab za "zones" button
    m = NAV_ANCHOR.search(html)
    if m:
        html = html[:m.end(1)] + NAV_TAB_HTML + html[m.end():]
        changed = True
    else:
        print(f'  ⚠️  nav anchor nenalezen: {os.path.basename(path)}')

    # 2. Insert page HTML před ADVANCED PAGE
    m2 = PAGE_INSERT_ANCHOR.search(html)
    if m2:
        html = html[:m2.start()] + PAGE_HTML + '\n\n  ' + m2.group(0) + html[m2.end():]
        changed = True
    else:
        print(f'  ⚠️  page anchor nenalezen: {os.path.basename(path)}')
        return False

    # 3. Insert CSS před </style>
    m3 = CSS_ANCHOR.search(html)
    if m3:
        html = html[:m3.start()] + CSS_HTML + m3.group(0) + html[m3.end():]
        changed = True

    # 4. Insert JS — hledáme existující Phase 15 marker end
    # Fallback: před </script></body>
    m4 = JS_ANCHOR.search(html)
    if m4:
        html = html[:m4.start()] + JS_CODE + '\n\n' + m4.group(0) + html[m4.end():]
        changed = True
    else:
        # Try inserting before closing </script>
        html = html.replace('</script>\n</body>', JS_CODE + '\n</script>\n</body>', 1)
        changed = True

    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)

    delta = len(html) - orig_len
    print(f'  ✓ patched: {os.path.basename(path)} ({delta:+d} bytes)')
    return True


def main():
    print('Phase 16: Heating page')
    ok = 0
    for p in FILES:
        if patch_file(p):
            ok += 1
    print(f'\nDone: {ok}/{len(FILES)} files patched')
    return 0 if ok == len(FILES) else 1


if __name__ == '__main__':
    sys.exit(main())
